<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PomodoroTimer</AssemblyName>
    <RootNamespace>PomodoroTimer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\background.png" Link="background.png"
          CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
    <None Include="..\..\assets\timer.mp3" Link="timer.mp3"
          CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
  </ItemGroup>
</Project>
